# file generated by Claude to test the added skill
# Remarks: Claude followed the skill as mentioned

require "rails_helper"

RSpec.describe "Projects", type: :request do
  fixtures :users

  let(:user) { users(:one) }
  let(:project) { Project.create!(title: "Existing Project") }
  let(:valid_params) { { project: { title: "My Project" } } }
  let(:invalid_params) { { project: { title: "" } } }

  describe "GET /projects" do
    context "when signed in" do
      before do
        post session_path, params: { email_address: user.email_address, password: "password" }
      end

      it "returns a successful response" do
        get projects_path
        expect(response).to have_http_status(:success)
      end
    end

    context "when not signed in" do
      it "redirects to the sign in page" do
        get projects_path
        expect(response).to redirect_to(new_session_path)
      end
    end
  end

  describe "GET /projects/:id" do
    context "when signed in" do
      before do
        post session_path, params: { email_address: user.email_address, password: "password" }
      end

      it "returns a successful response" do
        get project_path(project)
        expect(response).to have_http_status(:success)
      end
    end

    context "when not signed in" do
      it "redirects to the sign in page" do
        get project_path(project)
        expect(response).to redirect_to(new_session_path)
      end
    end
  end

  describe "GET /projects/new" do
    context "when signed in" do
      before do
        post session_path, params: { email_address: user.email_address, password: "password" }
      end

      it "returns a successful response" do
        get new_project_path
        expect(response).to have_http_status(:success)
      end
    end

    context "when not signed in" do
      it "redirects to the sign in page" do
        get new_project_path
        expect(response).to redirect_to(new_session_path)
      end
    end
  end

  describe "POST /projects" do
    context "when signed in with valid params" do
      before do
        post session_path, params: { email_address: user.email_address, password: "password" }
      end

      it "creates a project" do
        expect {
          post projects_path, params: valid_params
        }.to change(Project, :count).by(1)
      end

      it "redirects to the new project" do
        post projects_path, params: valid_params
        expect(response).to redirect_to(project_path(Project.last))
      end
    end

    context "when signed in with invalid params" do
      before do
        post session_path, params: { email_address: user.email_address, password: "password" }
      end

      it "does not create a project" do
        expect {
          post projects_path, params: invalid_params
        }.not_to change(Project, :count)
      end
    end

    context "when not signed in" do
      it "does not create a project" do
        expect {
          post projects_path, params: valid_params
        }.not_to change(Project, :count)
      end

      it "redirects to the sign in page" do
        post projects_path, params: valid_params
        expect(response).to redirect_to(new_session_path)
      end
    end
  end

  describe "PATCH /projects/:id" do
    context "when signed in" do
      before do
        post session_path, params: { email_address: user.email_address, password: "password" }
      end

      it "updates the project" do
        patch project_path(project), params: valid_params
        expect(project.reload.title).to eq("My Project")
      end

      it "redirects to the project" do
        patch project_path(project), params: valid_params
        expect(response).to redirect_to(project_path(project))
      end
    end

    context "when not signed in" do
      it "redirects to the sign in page" do
        patch project_path(project), params: valid_params
        expect(response).to redirect_to(new_session_path)
      end
    end
  end

  describe "DELETE /projects/:id" do
    before { project }

    context "when signed in" do
      before do
        post session_path, params: { email_address: user.email_address, password: "password" }
      end

      it "destroys the project" do
        expect {
          delete project_path(project)
        }.to change(Project, :count).by(-1)
      end

      it "redirects to the projects list" do
        delete project_path(project)
        expect(response).to redirect_to(projects_path)
      end
    end

    context "when not signed in" do
      it "does not destroy the project" do
        expect {
          delete project_path(project)
        }.not_to change(Project, :count)
      end
    end
  end
end
